/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appCanBeInstantiated() {
        App classUnderTest = new App();
        assertNotNull("app should be instantiated", classUnderTest);
    }
}
